### ISSUE TITLE
WSL Project Build Fail

### ISSUE THREAD

**Issue by mikart143** [alexkehayias/woz#5]
I am trying to test WOZ on WSL but I am keep getting an error.
I am using Pengwin.

>  Using project path /mnt/d/Projects/Rust/test-yew
Using config path /mnt/d/Projects/Rust/test-yew/woz.toml
Using home path /home/mikart143/.woz
Building...
    Finished release [optimized] target(s) in 0.11s
error: failed to read `/mnt/d/Projects/Rust/test-yew/target/wasm32-unknown-unknown/release/test-yew.wasm`
    caused by: No such file or directory (os error 2)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "wasm-bindgen failed" }
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized::hfe355cff142f3036 (0x6f5a16)
   1: backtrace::capture::Backtrace::new_unresolved::hdc76025a2db4ca85 (0x6f5814)
   2: <failure::backtrace::Backtrace as core::default::Default>::default::hf16bb97a923e949c (0x6f537e)
   3: <woz::components::wasm::WasmComponent as woz::components::AppComponent>::files::hf01327882f8bebbf (0x84ea83)
   4: woz::builder::AppBuilder::build::h29503a8d4e182ec6 (0x7cd1a9)
   5: woz::run::h5d20635ccd315fae (0x41f56e)
   6: woz::main::hb1f956e5b7bd9de9 (0x425965)
   7: std::rt::lang_start::{{closure}}::h6b103059a85eeaa6 (0x847752)
   8: main (0x426262)', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
  11: woz::builder::AppBuilder::build
  12: woz::run
  13: woz::main
  14: std::rt::lang_start::{{closure}}
  15: main

**Comment by alexkehayias** [comment]
looks like you haven’t installed wasm-bindgen which is required to run woz. Instructions for installing it are in the readme.
